# This is Dockerfile for building the database for koticloud demo.
FROM postgres:latest

RUN localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.UTF-8

COPY "./etc/schema.sql" "./docker-entrypoint-initdb.d/schema.sql"
