// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Infos           string
	NodeProcessReqs string
	Nodes           string
	Progress        string
	Users           string
}{
	Infos:           "infos",
	NodeProcessReqs: "node_process_reqs",
	Nodes:           "nodes",
	Progress:        "progress",
	Users:           "users",
}
