// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Infos           string
	Meta            string
	NodeProcessReqs string
	Nodes           string
	Users           string
}{
	Infos:           "infos",
	Meta:            "meta",
	NodeProcessReqs: "node_process_reqs",
	Nodes:           "nodes",
	Users:           "users",
}
